#!/bin/bash

export LC_ALL='en_US.UTF-8'

retry=10
DB_UIO=`ls -lt /sys/class/uio | grep debug_bridge | awk '{print $9}'`

while [ "$DB_UIO" == "" ] && [ $retry -ne 0 ]; do
   sleep 1
   DB_UIO=`ls -lt /sys/class/uio | grep debug_bridge | awk '{print $9}'`
   retry=$(( retry - 1 ))
done

if [ "$DB_UIO" == "" ]; then
   exit 1
fi


