# SC package feed URL - update when SC has its own package server
PACKAGE_FEED_URIS = "https://edf.amd.com/sswreleases/systemcontroller/2025.2/generic/rpm/rpm_latest/"

# Package feed names always use '_', while ARCH names might include -
PACKAGE_FEED_ARCHS ?= "${@d.getVar('PACKAGE_ARCHS').replace('-','_')}"
